### ISSUE TITLE
Pushing problems

### ISSUE THREAD

**Issue by CoryBrown-42** [CoryBrown42/gaming2D#7]
I have tried to push to the repo but it says i have restricted access. I can make commits but not pushes.

**Comment by scuhooper** [comment]
Cory,

It looks like that account just hasn't accepted the invite yet. Here is a copy of the link: https://github.com/scuhooper/gaming2D/invitations

Might try just logging in and accepting it again to see if it works. If you still have issues, I'll just cancel the invite and resend it.

James

**Comment by CoryBrown-42** [comment]
thank you
